services:
  selin-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selin-ai-app
    restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
      - WHISPER_BASE_URL=http://whisper:9000
    volumes:
      - ./data:/app/data

  redis:
    image: redis:alpine
    container_name: selin-ai-redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: selin-ai-whisper
    restart: always
    environment:
      - WHISPER_MODEL=small
      - WHISPER_LANGUAGE=ru
    ports:
      - "9000:9000"
    volumes:
      - whisper_cache:/root/.cache

volumes:
  redis_data:
  whisper_cache:
